manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: techphr33k
      url-base: https://github.com/techphr33k
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v4.1
      import: app/west.yml
  self:
    path: config
